"""rel_ship

Revision ID: 804e506f874e
Revises: 236710e0e046
Create Date: 2023-02-07 14:56:24.319275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804e506f874e'
down_revision = '236710e0e046'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
